ALTER TYPE "TableStatus" ADD VALUE IF NOT EXISTS 'WAITING_KITCHEN';
ALTER TYPE "TableStatus" ADD VALUE IF NOT EXISTS 'READY_TO_SERVE';
ALTER TYPE "TableStatus" ADD VALUE IF NOT EXISTS 'WAITING_PAYMENT';
